<?php
$width = isset($width) ? $width : "100%";
$height = isset($height) ? $height : "100%";
?>
<div
    id="<?= $id ?>"
    class="Loader-wrapper"
    data-visible="false"
    style="width: <?= $width ?>; height: <?= $height ?>;">
    <div class="Loader is-loading"></div>
</div>
<script
    type="text/javascript"
    data-loader-id="<?= $id ?>"
    src="<?= BASE_URI ?>/app/views/components/loader/script.js?v=<?= time() ?>"></script>
