<?php
$warpper_width = isset($warpper_width) ? $warpper_width : "100%";
$wrapper_height = isset($wrapper_height) ? $wrapper_height : "100%";

$loader_width = isset($loader_width) ? $loader_width : "80px";
$loader_height = isset($loader_height) ? $loader_height : "80px";
?>
<div
    id="<?= $id ?>"
    class="Loader-wrapper"
    data-visible="false"
    style="width: <?= $warpper_width ?>; height: <?= $wrapper_height ?>;">
    <div 
        class="Loader is-loading" 
        style="--loader-width: <?= $loader_width ?>; --loader-height: <?= $loader_height ?>;"></div>
</div>
<script
    type="text/javascript"
    data-loader-id="<?= $id ?>"
    src="<?= BASE_URI ?>/app/views/components/loader/script.js?v=<?= time() ?>"></script>
