<?php 
$session = $this->request->getSession();
$get = $this->request->getGet();
?>
<!-- jQuery -->
<script
    type="text/javascript"
    src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script
    type="text/javascript"
    src="https://code.jquery.com/ui/1.14.1/jquery-ui.min.js"></script>
<!-- Bulma -->
<link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css" />
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/bulma-toast/2.4.4/bulma-toast.min.js"
    integrity="sha512-Mblf9e5nxLeT5MxzmcT1L3Esj3sBqKxAXgq+SQUf0/eaJTBvx2RXA+VP3Qjpg2zDAYSSc/j6n1Gf6oU0CW2tqw=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"></script>
<!-- Icons -->
<script
    crossorigin="anonymous"
    src="https://kit.fontawesome.com/d5cb389dd1.js"></script>
<!-- Animate.css -->
<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
<?php if ($session["is_admin"]): ?>
    <!-- Quill.js -->
    <script 
        type="text/javascript"
        src="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.js"></script>
    <link 
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.snow.css" />
<?php endif; ?>
<!-- Local scripts -->
<script
    type="text/javascript"
    data-api-url="<?= API_URL ?>"
    data-base-url="<?= WEBSITE_URL ?>"
    src="<?= BASE_URI ?>/public/js/main.js?v=<?= $this->version ?>"></script>
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/public/js/functions.js?v=<?= $this->version ?>"></script>
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/public/js/api.js?v=<?= $this->version ?>"></script>
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/public/js/toast.js?v=<?= $this->version ?>"></script>
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/public/js/loader.js?v=<?= $this->version ?>"></script>
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/public/js/modal.js?v=<?= $this->version ?>"></script>
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/public/js/views.js?v=<?= $this->version ?>"></script>
<?php if ($get["admin"] && !$session["is_admin"]): ?>
    <script
        type="text/javascript"
        src="<?= BASE_URI ?>/public/js/admin-modal.js?v=<?= $this->version ?>"></script>
<?php elseif ($session["is_admin"]): ?>
    <script
        type="text/javascript"
        src="<?= BASE_URI ?>/public/js/admin.js?v=<?= $this->version ?>"></script>
    <script
        type="text/javascript"
        src="<?= BASE_URI ?>/public/js/media-library.js?v=<?= $this->version ?>"></script>
    <script
        type="text/javascript"
        src="<?= BASE_URI ?>/public/js/text-editor.js?v=<?= $this->version ?>"></script>
<?php endif; ?>
<!-- Local styles -->
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/public/css/main.css?v=<?= $this->version ?>" />
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/public/css/toast.css?v=<?= $this->version ?>" />
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/public/css/loader.css?v=<?= $this->version ?>" />
<?php if ($session["is_admin"]): ?>
    <link
        rel="stylesheet"
        href="<?= BASE_URI ?>/public/css/admin.css?v=<?= $this->version ?>" />
    <link
        rel="stylesheet"
        href="<?= BASE_URI ?>/public/css/text-editor.css?v=<?= $this->version ?>" />
<?php endif; ?>
