<?php 
$session = $this->request->getSession();
extract($session);
?>
<!-- jQuery -->
<script
    type="text/javascript"
    src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script
    type="text/javascript"
    src="https://code.jquery.com/ui/1.14.1/jquery-ui.min.js"></script>
<!-- Bulma -->
<link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css" />
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/bulma-toast/2.4.4/bulma-toast.min.js"
    integrity="sha512-Mblf9e5nxLeT5MxzmcT1L3Esj3sBqKxAXgq+SQUf0/eaJTBvx2RXA+VP3Qjpg2zDAYSSc/j6n1Gf6oU0CW2tqw=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"></script>
<!-- Icons -->
<script
    crossorigin="anonymous"
    src="https://kit.fontawesome.com/d5cb389dd1.js"></script>
<!-- Local scripts -->
<script
    type="text/javascript"
    data-api-url="<?= API_URL ?>"
    data-base-url="<?= WEBSITE_URL ?>"
    src="<?= BASE_URI ?>/public/js/main.js?v=<?= time() ?>"></script>
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/public/js/functions.js?v=<?= time() ?>"></script>
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/public/js/api.js?v=<?= time() ?>"></script>
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/public/js/toast.js?v=<?= time() ?>"></script>
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/public/js/loader.js?v=<?= time() ?>"></script>
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/public/js/views.js?v=<?= time() ?>"></script>
<?php if ($admin): ?>
    <script
        type="text/javascript"
        src="<?= BASE_URI ?>/public/js/adm.js?v=<?= time() ?>"></script>
<?php endif; ?>
<!-- Local styles -->
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/public/css/main.css?v=<?= time() ?>" />
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/public/css/toast.css?v=<?= time() ?>" />
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/public/css/loader.css?v=<?= time() ?>" />