<link
    rel="preconnect"
    href="https://fonts.googleapis.com" />
<link
    crossorigin
    rel="preconnect"
    href="https://fonts.gstatic.com" />
<!-- Josefin Slab -->
<link
    rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Josefin+Slab:ital,wght@0,100..700;1,100..700&display=swap" />
<!-- Merriweather -->
<link
    rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&display=swap" />
<!-- Georgia -->
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/public/fonts/Georgia.ttf" />
