<?php
$id = !isset($id) ? "modal" : $id;
$onclose = !isset($onclose) ? "window.modal.hide()" : $onclose;
$hide_footer = !isset($hide_footer) ? false : $hide_footer;
?>

<div id="<?= $id ?>" class="modal">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title title is-5" data-field="title"></p>
            <button 
                class="delete" 
                aria-label="close"
                onclick="<?= $onclose ?>"
            ></button>
        </header>
        <section class="modal-card-body">
            <div class="content" data-field="content"></div>
        </section>
        <?php if (!$hide_footer): ?> 
            <footer class="modal-card-foot" data-field="footer" data-visible="true"></footer>
        <?php endif; ?>
    </div>
</div>
