<div id="modal" class="modal">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title" data-field="title"></p>
            <button 
                class="delete" 
                aria-label="close"
                onclick="window.modal.hide()"
            ></button>
        </header>
        <section class="modal-card-body">
            <div class="content" data-field="content"></div>
        </section>
        <footer class="modal-card-foot" data-field="footer"></footer>
    </div>
</div>
