<?php
extract($query);

$session = $this->request->getSession();
$categories = $session["categories"];
$current_path = $this->request->getPath();
$is_home = $current_path === "/";

if (!isset($search)) {
    $search = "";
}

if (!isset($category)) {
    $category = null;
}
?>
<aside
    <?php if ($is_home): ?>
    id="post-filters"
    data-view="post-filters"
    <?php endif; ?>
    class="Filters">
    <div class="Searchbar-container">
        <label class="Searchbar-label">
            <span class="Searchbar-text">
                <input
                    id="search-bar"
                    class="Searchbar-input"
                    type="text"
                    placeholder="Pesquise aqui e aperte Enter..."
                    onkeypress="handleSearchOnEnter(event)"
                    value="<?= $search ?>" />
            </span>
            <span class="Searchbar-icon" onclick="handleSearch(event)">
                <i class="fa-solid fa-magnifying-glass"></i>
            </span>
        </label>
    </div>
    <div class="Categories-container">
        <h3 class="Categories-title title">
            Categorias
        </h3>
        <ul class="Categories-list">
            <?php foreach ($categories as $ctg): ?>
                <li>
                    <a
                        <?php if ($is_home): ?>
                        href="<?= "javascript:handleApplyFilter('category', '$ctg[name]')" ?>"
                        <?php else: ?>
                        href="<?= BASE_URI . "/?category=$ctg[name]" ?>"
                        <?php endif; ?>
                        <?php if ($category === $ctg["name"]): ?>
                        class="active"
                        <?php endif; ?>>
                        <?= $ctg["name"] ?>
                    </a>
                    (<?= $ctg["post_count"] ?>)
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</aside>
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/app/views/components/filters/styles.css?v=<?= time() ?>" />
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/app/views/components/filters/script<?= $is_home ? "-home" : "-others" ?>.js?v=<?= time() ?>"></script>