<?php
if (!isset($query)) {
    $query = [];
}

extract($query);

$session = $this->request->getSession();
$categories = $session["categories"];
$is_authenticated = $session["is_authenticated"];
$current_path = $this->request->getPath();
$is_home = $current_path === "/";

if (!isset($search)) {
    $search = "";
}

if (!isset($category)) {
    $category = null;
}
?>
<aside
    <?php if ($is_home): ?>
    id="post-filters"
    data-view="post-filters"
    <?php endif; ?>
    class="Filters">
    <div class="Searchbar-container">
        <label class="Searchbar-label">
            <span class="Searchbar-text">
                <input
                    id="search-bar"
                    class="Searchbar-input"
                    type="text"
                    placeholder="Pesquise aqui e aperte Enter..."
                    onkeypress="handleSearchOnEnter(event)"
                    value="<?= $search ?>" />
            </span>
            <span class="Searchbar-icon" onclick="handleSearch($('#search-bar')[0])">
                <i class="fa-solid fa-magnifying-glass"></i>
            </span>
        </label>
    </div>
    <div class="Categories-container">
        <h3 class="Categories-title title">
            Categorias
        </h3>
        <ul class="Categories-list">
            <?php foreach ($categories as $ctg): ?>
                <li>
                    <span>
                        <a
                            <?php if ($is_home): ?>
                                href="javascript:handleApplyFilter('category', '<?=$ctg["name"]?>')"
                            <?php else: ?>
                                href="<?= BASE_URI . "/?category=$ctg[name]" ?>"
                            <?php endif; ?>
                            <?php if ($category === $ctg["name"]): ?>
                                class="active"
                            <?php endif; ?>
                            <?php if ($is_authenticated): ?>
                                data-category-id="<?=$ctg["id"]?>"
                                data-category-name="<?=$ctg["name"]?>"
                                contenteditable="true"
                            <?php endif; ?>
                        >
                            <?= $ctg["name"] ?>
                        </a>
                        (<?= $ctg["post_count"] ?>)
                    </span>
                    <?php if ($is_authenticated): ?>
                        <button 
                            class="DeleteButton button is-danger is-rounded" 
                            onclick="handleDeleteCategory(this, <?=$ctg['id']?>)"
                        >
                            <i class="fa-solid fa-trash"></i>
                        </button>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <link
        rel="stylesheet"
        href="<?= BASE_URI ?>/app/views/components/filters/styles.css?v=<?= time() ?>" />
    <script
        type="text/javascript"
        src="<?= BASE_URI ?>/app/views/components/filters/script<?= $is_home ? "-home" : "-others" ?>.js?v=<?= time() ?>"></script>
</aside>
