<?php 
$session = $this->request->getSession();
extract($session);
extract($settings);
$writer_photo = hide_base_path($writer_photo, BASE_URI);
$writer_photo = BASE_URI . $writer_photo;
?>
<section class="AboutMe">
    <aside class="AboutMe-aside">
        <figure class="AboutMe-photo">
            <?php if ($is_admin): ?>
                <button 
                    class="AboutMe-changePhoto button is-info icon-button is-large" 
                    onclick="handleChangeProfilePhoto()"
                >
                    <i class="fa-solid fa-camera-retro"></i>
                </button>
            <?php endif; ?>
            <img 
                src="<?= $writer_photo ?>" 
                alt="Foto de <?= $writer_name ?>"
                <?php if ($is_admin): ?>
                    data-settings="writer_photo"
                <?php endif; ?>
            >
        </figure>
        <h2
            class="title"
            <?php if ($is_admin): ?>
                contenteditable="true"
                data-settings="writer_name"
            <?php endif; ?>
        >
            <?= $writer_name ?>
        </h2>
    </aside>
    <main class="AboutMe-main">
        <div 
            class="AboutMe-text content"
            <?php if ($is_admin): ?>
                contenteditable="true"
                data-settings="writer_about"
            <?php endif; ?>
        >
            <?= $writer_about ?>
        </div>
    </main>
</section>

<link rel="stylesheet" href="<?= BASE_URI ?>/app/views/pages/about-me/styles.css?v=<?= $this->version ?>">
<script type="text/javascript" src="<?= BASE_URI ?>/app/views/pages/about-me/script.js?v=<?= $this->version ?>"></script>
