<?php $current_path = $this->request->getPath() ?>
<div class="AdminActions">
    <button
        class="AdminActions-action AdminActions-save button is-warning"
        type="button"
        onclick="handleResetChanges(this)"
        title="Resetar alterações"
    >
        <i class="fa-solid fa-eraser"></i>
        <span>Resetar alterações</span>
    </button>
    <button
        class="AdminActions-action AdminActions-reset button is-success"
        type="button"
        onclick="handleSaveChanges(this)"
        title="Salvar alterações"
    >
        <i class="fa-solid fa-floppy-disk"></i>
        <span>Salvar alterações</span>
    </button>
    <?php if (str_contains($current_path, "/posts/")): ?>
        <button
            class="AdminActions-action AdminActions-loadDrafts button"
            type="button"
            onclick="handleLoadDraft(this)"
            title="Sair"
        >
            <i class="fa-solid fa-pen-ruler"></i>
            <span>Carregar rascunho</span>
        </button>
        <button
            class="AdminActions-action AdminActions-saveDraft button"
            type="button"
            onclick="handleSaveDraft(this)"
            title="Sair"
        >
            <i class="fa-solid fa-box-archive"></i>
            <span>Salvar rascunho</span>
        </button>
    <?php else: ?>
        <button
            class="AdminActions-action AdminActions-write button"
            type="button"
            onclick="window.open('<?= BASE_URI ?>/posts/new')"
            title="Sair"
        >
            <i class="fa-solid fa-pencil"></i>
            <span>Escrever novo post</span>
        </button>
    <?php endif; ?>
    <button
        class="AdminActions-action AdminActions-logout button is-info"
        type="button"
        onclick="handleLogout(this)"
        title="Sair"
    >
        <i class="fa fa-sign-out"></i>
        <span>Sair</span>
    </button>
</div>
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/app/views/components/admin-actions/styles.css?v=<?= time() ?>" />
