<?php 
$session = $this->request->getSession();
extract($session);
?>
<!DOCTYPE html>
<html lang="pt">

<head>
    <?php
    $this->component("meta-tags", [
        "description" => $description,
        "keywords"    => $keywords
    ])
    ?>
    <title><?= $title ?></title>
    <?php $this->component("fonts") ?>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.14.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.1.1/gsap.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css" />
    <script crossorigin="anonymous" src="https://kit.fontawesome.com/d5cb389dd1.js"></script>
    <link rel="stylesheet" href="<?= BASE_URI ?>/public/css/main.css?v=<?= $this->version ?>" />
    <link rel="stylesheet" href="<?= BASE_URI ?>/app/views/pages/404/styles.css?v=<?= $this->version ?>">
</head>

<body>
    <?php $this->component("navbar") ?>
    <main class="PageNotFound">
        <div class="PageNotFound-inner">
            <aside class="PageNotFound-figure">
                <?= $this->page("404/astronaut") ?>
            </aside>
            <div class="PageNotFound-text">
                <h1 class="title is-1">404</h1>
                <h2 class="subtitle is-3">Poxa! Você se perdeu.</h2>
                <p>A página que você está procurando não existe. Como você chegou aqui é um mistério. Mas você pode clicar <a href="<?= BASE_URI ?>">aqui</a> para voltar à página inicial.</p>
            </div>
        </div>
    </main>
    <?php $this->component("back-to-top") ?>
    <script type="text/javascript" src="<?= BASE_URI ?>/app/views/pages/404/script.js?v=<?= $this->version ?>"></script>
</body>

</html>
