<?php 
$session = $this->request->getSession();
extract($session);
?>
<!DOCTYPE html>
<html lang="pt">

<head>
    <?php
    $this->component("meta-tags", [
        "description" => $description,
        "keywords"    => $keywords
    ])
    ?>
    <title><?= $title ?></title>
    <?php $this->component("fonts") ?>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css" />
    <script crossorigin="anonymous" src="https://kit.fontawesome.com/d5cb389dd1.js"></script>
    <link rel="stylesheet" href="<?= BASE_URI ?>/public/css/main.css?v=<?= $this->version ?>" />
    <link rel="stylesheet" href="<?= BASE_URI ?>/app/views/pages/404/styles.css?v=<?= $this->version ?>">
</head>

<body>
    <?php $this->component("navbar") ?>
    <?php $this->component("back-to-top") ?>
</body>

</html>
