<?php 
$session = $this->request->getSession();
extract($session);
?>
<!DOCTYPE html>
<html lang="pt">

<head>
    <?php
    $this->component("meta-tags", [
        "description" => $description,
        "keywords"    => $keywords
    ])
    ?>
    <title><?= $title ?></title>
    <?php $this->component("dependencies") ?>
    <?php $this->component("fonts") ?>
</head>

<body>
    <?php $this->component("navbar") ?>
    <?php $this->component("back-to-top") ?>
    <?php $this->component("modal") ?>
    <?php if ($is_admin):
        $this->component("admin-actions");
    endif; ?>
    <link rel="stylesheet" href="<?= BASE_URI ?>/app/views/pages/404/styles.css?v=<?= $this->version ?>">
</body>

</html>
