<div
    id="comment-form"
    data-view="comment-form"
    class="AddComment">
    <header class="AddComment-header">
        <h3 class="title is-5">
            Adicionar Comentário
        </h3>
        <p class="subtitle is-6">
            Seu endereço de email não será publicado
        </p>
    </header>
    <form class="AddComment-form" onsubmit="handleSendComment(this, event)">
        <fieldset>
            <input
                type="hidden"
                name="post_id"
                value="<?= $post["id"] ?>" />
            <?php if (isset($reply_to_comment)): ?>
                <input
                    type="hidden"
                    name="reply_to"
                    value="<?= $reply_to_comment["id"] ?>" />
            <?php endif; ?>
            <input
                required
                class="input is-normal"
                type="text"
                name="fullname"
                placeholder="Seu nome" />
            <input
                required
                class="input is-normal"
                type="email"
                name="email"
                placeholder="Seu email" />
            <textarea
                required
                class="textarea"
                name="comment"
                placeholder="Seu comentário..."
                rows="10"></textarea>
            <button class="button is-success is-fullwidth" type="submit">
                Enviar comentário
            </button>
        </fieldset>
    </form>
</div>