<?php 
if (!isset($rows)) {
    $rows = 10;
}

if (!isset($visible)) {
    $visible = true;
}
?>
<div
    id="comment-form-<?= isset($reply_to_comment) ? $reply_to_comment["id"] : "" ?>"
    data-view="comment-form"
    data-visible="<?= json_encode($visible) ?>"
    class="AddComment">
    <?php if (!isset($reply_to_comment)): ?>
        <header class="AddComment-header">
            <h3 class="title is-5">
                Adicionar Comentário
            </h3>
            <p class="subtitle is-6">
                Seu endereço de email não será publicado
            </p>
        </header>
    <?php endif; ?>
    <form class="AddComment-form" onsubmit="handleSendComment(this, event)">
        <?php if (isset($reply_to_comment)): ?>
            <p class="title is-6 m-0 has-text-weight-normal is-italic">
                Respondendo a <?= $reply_to_comment["first_name"] ?> <?= $reply_to_comment["last_name"] ?>...
            </p>
        <?php endif; ?>
        <fieldset>
            <input
                type="hidden"
                name="post_id"
                value="<?= $post["id"] ?>" />
            <?php if (isset($reply_to_comment)): ?>
                <input
                    type="hidden"
                    name="reply_to"
                    value="<?= $reply_to_comment["id"] ?>" />
            <?php endif; ?>
            <input
                required
                class="input is-normal"
                type="text"
                name="fullname"
                placeholder="Seu nome" />
            <input
                required
                class="input is-normal"
                type="email"
                name="email"
                placeholder="Seu email" />
            <textarea
                required
                class="textarea"
                name="comment"
                placeholder="Seu comentário..."
                rows="<?= $rows ?>"></textarea>
            <button class="button is-success is-fullwidth" type="submit">
                Enviar comentário
            </button>
        </fieldset>
    </form>
</div>
