<?php 
$url = UPLOAD_URI.$path;
?>

<section class="MediaLibrary-file">
    <div class="MediaLibrary-file-viewer">
        <object 
            type="<?= $mimetype ?>"
            name="<?= $name ?>"
            data="<?= $url ?>"
        ></object>
    </div>
    <ul class="MediaLibrary-file-info">
        <li>
            Nome: <span 
                contenteditable="true"
                onfocusout="handleRenameMediaItem(event, '<?= $path ?>', '<?= $name ?>')"
            ><?= $name ?></span>
            <i class="fa-solid fa-pencil"></i>
        </li>
        <li>
            Localização: <b><?= $path ?></b>
        </li>
        <li>
            Link: <a href="<?= $url ?>" target="_blank">
                Abrir <i class="fa-solid fa-arrow-up-right-from-square"></i>
            </a>
        </li>
        <li>
            Tipo: <b><?= $mimetype ?></b>
        </li>
        <li>
            Última modificação em <b><?= $modification_time ?></b>
        </li>
        <li>
            Último acesso em <b><?= $access_time ?></b>
        </li>
        <li>
            Criado em <b><?= $creation_time ?></b>
        </li>
    </ul>
</section>
