<?php 
$url = UPLOAD_URI.$path;
?>

<section class="MediaLibrary-file">
    <div class="MediaLibrary-file-viewer">
        <object 
            type="<?= $mimetype ?>"
            name="<?= $name ?>"
            data="<?= $url ?>"
        ></object>
    </div>
    <ul class="MediaLibrary-file-info">
        <li>
            Nome: <span 
                contenteditable="true"
                onfocusout="handleRenameMediaItem(event, '<?= $path ?>', '<?= $name ?>')"
            ><?= $name ?></span>
        </li>
        <li>
            Localização: <?= $path ?>
        </li>
        <li>
            Link: <a href="<?= $url ?>" target="_blank">
                Abrir <i class="fa-solid fa-arrow-up-right-from-square"></i>
            </a>
        </li>
        <li>
            Tipo: <?= $mimetype ?>
        </li>
        <li>
            Última modificação em <?= $modification_time ?>
        </li>
        <li>
            Último acesso em <?= $access_time ?>
        </li>
        <li>
            Criado em <?= $creation_time ?>
        </li>
    </ul>
</section>
