<?php 
$directory_path = UPLOAD_PATH;
if (isset($base_path)) {
    $parts = explode("/", UPLOAD_PATH);

    foreach ($parts as $part) {
        $base_path = str_replace($part, "", $base_path);
    }

    $base_path = preg_replace("/\/+/", "/", $base_path);

    $directory_path .= "/$base_path";
}
$directory_path = preg_replace("/\/+/", "/", $directory_path);

$map = map_directory($directory_path, DEFAULT_DISPLAY_DATETIME_FORMAT);
$map = $map[0]["children"];
?>
<div
    id="media-library"
    class="MediaLibrary"
    data-view="media-library"
>
    <header class="MediaLibrary-header">
        <div class="MediaLibrary-current"></div>
        <div class="MediaLibrary-actions">
            <button class="MediaLibrary-uploadFile button is-info is-outlined">
                <i class="fa-regular fa-file"></i>
                <span>Novo arquivo</span>
            </button> 
            <button class="MediaLibrary-addFolder button is-success is-outlined">
                <i class="fa-regular fa-folder"></i>
                <span>Nova pasta</span>
            </button> 
        </div>
    </header>
    <main class="MediaLibrary-main">
        <ul class="MediaLibrary-items">
            <?php foreach ($map as $item): ?>
                <li 
                    class="MediaLibrary-item" 
                    onclick="handleOpenItem('<?= $item['type'] ?>', '<?= $item['path'] ?>')"
                >
                    <?php $this->component("media-library/$item[type]", $item) ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </main>
    <footer class="MediaLibrary-footer"></footer>
</div>
<link 
    rel="stylesheet" 
    href="<?= BASE_URI ?>/app/views/components/media-library/styles.css?v=<?= time() ?>"
/>
<script 
    type="text/javascript" 
    src="<?= BASE_URI ?>/app/views/components/media-library/script.js?v=<?= time() ?>"
></script>
