<?php 
$base_path = isset($base_path) ? $base_path : "";
$is_file = is_type_file($base_path);
$directory_path = get_directory_path($base_path);
$map = get_directory_map($directory_path);
?>
<div
    id="media-library"
    class="MediaLibrary"
    data-view="media-library"
>
    <header class="MediaLibrary-header">
        <div class="MediaLibrary-actions">
            <button 
                class="MediaLibrary-uploadFile button is-info"
                onclick="handleUploadFile()"
            >
                <i class="fa-regular fa-file"></i>
                <span>Novo arquivo</span>
            </button> 
            <button class="MediaLibrary-addFolder button is-success">
                <i class="fa-regular fa-folder"></i>
                <span>Nova pasta</span>
            </button> 
        </div>
        <div class="MediaLibrary-current">
            <?php $this->component("media-library/breadcrumb", ["directory_path" => $directory_path]) ?>
        </div>
    </header>
    <main class="MediaLibrary-main">
        <?php if ($is_file): 
            $file_path = get_file_path($base_path);
            $item = extract_data_from_path($file_path, DEFAULT_DISPLAY_DATETIME_FORMAT);
            $secure_path = get_secure_path($item);
            $item["path"] = $secure_path;
            $this->component("media-library/file-viewer", $item);
        endif; ?>
        <ul class="MediaLibrary-items">
            <?php foreach ($map as $item): 
                $path = get_secure_path($item);
                ?>
                <li 
                    class="MediaLibrary-item" 
                    onclick="handleOpenItem('<?= $path ?>')"
                    title="<?= $item["name"] ?>"
                >
                    <?php $this->component("media-library/$item[type]", $item) ?>
                    <span class="MediaLibrary-item-actions">
                        <button 
                            class="button is-danger icon-button"
                            onclick="handleOpenMediaItemDeletionModal(event, '<?= $path ?>')"    
                        >
                            <i class="fa-solid fa-trash"></i>
                        </button>
                    </span>
                </li>
            <?php endforeach; ?>
        </ul>
    </main>
    <footer class="MediaLibrary-footer"></footer>
    <?php $this->component("modal", [
        "id" => "media-library-modal",
        "onclose" => "window.admin.mediaLibrary.modal.hide()"
    ]) ?>
</div>
<link 
    rel="stylesheet" 
    href="<?= BASE_URI ?>/app/views/components/media-library/styles.css?v=<?= time() ?>"
/>
<script 
    type="text/javascript" 
    src="<?= BASE_URI ?>/app/views/components/media-library/script.js?v=<?= time() ?>"
></script>
<?php 

function get_directory_path(string $base_path)
{
    $is_file = is_type_file($base_path);
    if ($is_file) {
        $base_path = preg_replace("/\/[^\/]+\.\w+$/", "", $base_path);
    }

    $directory_path =  UPLOAD_PATH."/$base_path";
    return $directory_path;
}

function get_file_path(string $base_path)
{
    $file_path =  UPLOAD_PATH."/$base_path";
    $file_path = preg_replace("/\/+/", "/", $file_path);
    return $file_path;
}

function get_directory_map(string $directory_path) 
{
    $map = map_directory($directory_path, DEFAULT_DISPLAY_DATETIME_FORMAT);
    $map = $map[0]["children"];
    return $map;
}

function get_secure_path(array $item)
{
    return hide_base_path($item["path"], UPLOAD_PATH);
}

function get_src(string $extension, string $file_path): string {
    $src = "/public/images/media-library/files/file.png";

    $is_image = preg_match("/\.(jpg|jpeg|svg|png|gif|tiff|bmp|webp)$/", $file_path);
    if ($is_image && file_exists($file_path)) {
        $image_src = hide_base_path($file_path, ROOT_PATH);
        $src = $image_src;
    } else {
        $icon_src = ROOT_PATH."/public/images/media-library/files/$extension.png";
        
        if (file_exists($icon_src)) {
            $icon_src = hide_base_path($icon_src, ROOT_PATH);
            $src = $icon_src;
        }
    }
    
    $src = BASE_URI.$src;

    return $src;
}

function is_type_file(string $path): bool 
{
    return (bool)preg_match("/\.\w+$/", $path);
}
