<!DOCTYPE html>
<html lang="pt">

<head>
    <?php
    $this->component("meta-tags", [
        "description" => $description,
        "keywords"    => $keywords
    ])
    ?>
    <title><?= $title ?></title>
    <?php $this->component("dependencies") ?>
    <?php $this->component("fonts") ?>
</head>

<body>
    <?php
    $this->component("navbar", [
        "active_page" => "home",
    ]);
    ?>
    <header class="Header">
        <div class="Header-inner">
            <h1 class="Header-title title is-3">
                <a href="<?= BASE_URI ?>">
                    <?= APP_NAME ?>
                </a>
            </h1>
            <p class="Header-subtitle subtitle">
                Minha caixinha de pensamentos
            </p>
        </div>
    </header>
    <main class="Main">
        <ul class="RecentPosts">
            <?php
            $this->component("loader", [
                "id" => "postsLoader",
            ]);
            $this->view("home/post-card", [
                "id"             => "",
                "slug"           => "",
                "title"          => "",
                "text"           => "",
                "created_at"     => "",
                "category_names" => "",
            ]);
            foreach ($recent_posts as $post):
                $this->view("home/post-card", $post);
            endforeach;
            ?>
        </ul>
        <aside class="Filters">
            <div class="Searchbar-container">
                <label class="Searchbar-label">
                    <span class="Searchbar-text">
                        <input
                            class="Searchbar-input"
                            type="text"
                            placeholder="Pesquise aqui e aperte Enter..."
                            onkeypress="handleSearch(event)" />
                    </span>
                    <span class="Searchbar-icon">
                        <i class="fa-solid fa-magnifying-glass"></i>
                    </span>
                </label>
            </div>
            <div class="Categories-container">
                <h3 class="Categories-title title">
                    Categorias
                </h3>
                <ul class="Categories-list">
                    <?php foreach ($categories as $category): ?>
                        <li>
                            <a
                                href="javascript:void(0)"
                                data-filter-key="category"
                                data-filter-value="<?= $category["name"] ?>"
                                onclick="handleApplyFilter(this)">
                                <?= $category["name"] ?>
                            </a>
                            (<?= $category["post_count"] ?>)
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </aside>
    </main>
    <?php
    $this->component("back-to-top");
    ?>
    <link rel="stylesheet" href="app/views/pages/home/styles.css?v=<?= time() ?>" />
    <style type="text/css">
        .Header {
            --header-background-image: url(<?= $header_image ?>);
        }
    </style>
    <script type="text/javascript" src="app/views/pages/home/script.js?v=<?= time() ?>"></script>
</body>

</html>
