<?php
$session = $this->request->getSession();
extract($session);

$summary = generate_summary($text);

$post_categories = explode(",", $category_names);
$total_categories = count($post_categories);
$last_category_index = $total_categories - 1;
?>

<li class="PostCard PostCard-listItem" data-post-id="<?= $id ?>">
    <article class="PostCard-container">
        <header class="PostCard-header">
            <h2 class="PostCard-title title">
                <a href="<?= BASE_URI ?>/posts/<?= $slug ?>">
                    <?= $title ?>
                </a>
            </h2>
            <div class="PostCard-subheader">
                <?php if ($is_admin): ?>
                    <span class="PostCard-date">
                        Escrito em <?= $created_at ?>
                    </span>
                    <span class="PostCard-date">
                        Atualizado em <?= $updated_at ?>
                    </span>
                <?php endif; ?>
                <?php if ($published): ?>
                    <span class="PostCard-date">
                        Publicado em <?= $published_at ?>
                    </span>
                <?php elseif ($is_admin): ?>
                    <span class="PostCard-date">
                        [Não publicado ainda!]
                    </span>
                <?php endif; ?>
                <span class="PostCard-categories">
                    <?php foreach ($post_categories as $i => $category_name): ?>
                        <a class="PostCard-category" href="javascript:void(0)" data-filter-key="category"
                            data-filter-value="<?= $category_name ?>" onclick="handleApplyFilter(this)">
                            <?= $category_name ?>
                        </a><?= $i !== $last_category_index ? ", " : "" ?>
                    <?php endforeach; ?>
                </span>
            </div>
        </header>
        <div class="PostCard-summary">
            <?= $summary ?>
        </div>
    </article>
</li>