<?php
$is_template = !(bool)$id;
$created_at = strtotime($created_at);
$created_at = date("d/m/Y, H:i:s", $created_at);
$post_categories = explode(",", $category_names);
$total_categories = count($post_categories);
$last_category_index = $total_categories - 1;
?>

<li
    class="PostCard PostCard-listItem"
    data-post-id="<?= $id ?>"
    data-template="<?= json_encode($is_template) ?>">
    <article class="PostCard-container">
        <header class="PostCard-header">
            <h2 class="PostCard-title title">
                <a href="<?= BASE_URI ?>/posts/<?= $slug ?>" data-column="title">
                    <?= $title ?>
                </a>
            </h2>
            <div class="PostCard-subheader">
                <span
                    class="PostCard-createdAt"
                    data-column="created_at"><?= $created_at ?></span>
                <span
                    class="PostCard-categories"
                    data-column="category_names">
                    <?php foreach ($post_categories as $i => $category_name): ?>
                        <a
                            class="PostCard-category"
                            href="javascript:void(0)"
                            data-filter-key="category"
                            data-filter-value="<?= $category_name ?>"
                            onclick="handleApplyFilter(this)">
                            <?= $category_name ?>
                        </a><?= $i !== $last_category_index ? ", " : "" ?>
                    <?php endforeach; ?>
                </span>
            </div>
        </header>
        <div
            class="PostCard-text"
            data-column="text">
            <?= $text ?>
        </div>
    </article>
</li>
