<?php
$session = $this->request->getSession();
extract($session);

$post_count = count($post_list);
$no_posts = $post_count === 0;
$show_no_posts_msg = $no_posts;
$show_filter_title = (
    (array_key_exists("search", $query) && (bool)$query["search"]) ||
    (array_key_exists("category", $query) && (bool)$query["category"])
);

$filter_msg = "Posts encontrados";

if (array_key_exists("category", $query)) {
    $filter_msg .= " em \"$query[category]\"";
}

if (array_key_exists("search", $query)) {
    $filter_msg .= " com o texto \"$query[search]\"";
}

$filter_msg .= "...";
?>

<ul
    id="post-list"
    class="PostList"
    data-view="post-list"
>
    <?php if ($show_filter_title): ?>
        <li
            id="filter-title"
            class="subtitle is-5 is-italic"
        >
            <span><?= $filter_msg ?></span>
            <a href="javascript:handleClearFilters()">Limpar</a>
        </li>
    <?php endif;
    if ($show_no_posts_msg): ?>
        <li id="no-posts-message" class="NoPostFound">
            <img
                class="image is-128x128"
                src="public/images/planet.png"
                alt="Planeta">
            <h2 class="title is-4">
                Nenhum post encontrado
            </h2>
            <p class="subtitle is-6">
                Parece que ainda não há posts recentes. Volte mais tarde para ver as novidades!
            </p>
        </li>
    <?php endif;
    foreach ($post_list as $post):
        $this->view("home/post-card", format_post_dates($post));
    endforeach;
    ?>
</ul>

<?php 

function format_post_dates(array $post): array 
{
    if (date_is_valid($post["created_at"])) {
        $post["created_at"] = strtotime($post["created_at"]);
        $post["created_at"] = strftime(DEFAULT_DISPLAY_DATETIME_FORMAT, $post["created_at"]);
    }
    
    if (date_is_valid($post["updated_at"])) {
        $post["updated_at"] = strtotime($post["updated_at"]);
        $post["updated_at"] = strftime(DEFAULT_DISPLAY_DATETIME_FORMAT, $post["updated_at"]);
    }
    
    if (isset($post["published_at"]) && date_is_valid($post["published_at"])) {
        $post["published_at"] = strtotime($post["published_at"]);
        $post["published_at"] = strftime(DEFAULT_DISPLAY_DATETIME_FORMAT, $post["published_at"]);
    }

    return $post;
}