<?php
$post_count = count($post_list);
$no_posts = $post_count === 0;
$show_no_posts_msg = $no_posts;
$show_filter_title = (
    (array_key_exists("search", $get) && (bool)$get["search"]) ||
    (array_key_exists("category", $get) && (bool)$get["category"])
);
?>

<ul class="RecentPosts">
    <?php if ($show_filter_title): ?>
        <li
            id="filter-title"
            class="subtitle is-5 is-italic">
            <span></span>
            <a href="javascript:void(0)" onclick="handleClearFilters()">Limpar</a>
        </li>
    <?php endif; 
    $this->component("loader", ["id" => "postsLoader"]);
    if ($show_no_posts_msg): ?>
        <li id="no-posts-message" class="NoPostFound">
            <img
                class="image is-128x128"
                src="public/images/planet.png"
                alt="Planeta" />
            <h2 class="title is-4">
                Nenhum post encontrado
            </h2>
            <p class="subtitle is-6">
                Parece que ainda não há posts recentes. Volte mais tarde para ver as novidades!
            </p>
        </li>
    <?php endif; 
    $this->view("home/post-card", [
        "id"             => ":id",
        "slug"           => ":slug",
        "title"          => ":title",
        "text"           => ":text",
        "created_at"     => ":created_at",
        "updated_at"     => ":updated_at",
        "category_names" => ":category_name",
    ]);
    foreach ($recent_posts as $post):
        $this->view("home/post-card", $post);
    endforeach;
    ?>
</ul>