<?php
extract($comment);

$fullname = "$first_name $last_name";

$initials = get_initials($fullname);
$initials = array_map("strtoupper", $initials);
$initials = [$initials[0], $initials[count($initials) - 1]];
$initials = implode("", $initials);
$avatar_color = text_to_color($initials);

if (date_is_valid($created_at)) {
    $created_at = strtotime($created_at);
    $created_at = strftime(DEFAULT_DISPLAY_DATETIME_FORMAT, $created_at);
}

?>

<li class="Comment" data-comment-id="<?= $id ?>">
    <?php if (!isset($photo) || !file_exists($photo)): ?>
        <div class="Comment-avatar" style="background-color: <?= $avatar_color ?>;">
            <?= $initials ?>
        </div>
    <?php else: ?>
        <img
            class="Comment-photo"
            src="<?= BASE_URI . $photo ?>"
            alt="Foto de <?= $fullname ?>" />
    <?php endif; ?>
    <div class="Comment-content">
        <div class="Comment-info">
            <p class="Comment-author">
                <?= $fullname ?>
            </p>
            <div class="Comment-meta">
                <p class="Comment-time">
                    <?= $created_at ?>
                </p>
                <button class="Comment-reply">
                    Responder
                </button>
            </div>
        </div>
        <div class="Comment-text">
            <?= $text ?>
        </div>
    </div>
</li>
