<?php
extract($comment);

$fullname = "$first_name $last_name";

$initials = get_initials($fullname);
$initials = array_map("strtoupper", $initials);
$initials = [$initials[0], $initials[count($initials) - 1]];
$initials = implode("", $initials);
$avatar_color = text_to_color($initials);

if (date_is_valid($created_at)) {
    $created_at = strtotime($created_at);
    $created_at = strftime(DEFAULT_DISPLAY_DATETIME_FORMAT, $created_at);
}

$reply_comments = array_filter($all_post_comments, function ($comm) use ($id) {
    return $comm["comment_id"] === $id;
});
?>

<li class="CommentCard" data-comment-id="<?= $id ?>">
    <?php if (!isset($photo) || !file_exists($photo)): ?>
        <div class="CommentCard-avatar" style="background-color: <?= $avatar_color ?>;">
            <?= $initials ?>
        </div>
    <?php else: ?>
        <img
            class="CommentCard-photo"
            src="<?= BASE_URI . $photo ?>"
            alt="Foto de <?= $fullname ?>" />
    <?php endif; ?>
    <div class="CommentCard-content">
        <div class="CommentCard-info">
            <p class="CommentCard-author">
                <?= $fullname ?>
            </p>
            <div class="CommentCard-meta">
                <p class="CommentCard-time">
                    <?= $created_at ?>
                </p>
                <button
                    class="CommentCard-reply"
                    onclick="handleOpenReplyForm('<?= $id ?>')">
                    Responder
                </button>
            </div>
        </div>
        <p class="CommentCard-text"><?= $text ?></p>
        <ul
            class="CommentCard-replies"
            data-visible="<?= count($reply_comments) > 0 ? "true" : "false" ?>">
            <?php
            foreach ($reply_comments as $comm):
                $this->view("posts/comment-card", [
                    "comment"           => $comm,
                    "all_post_comments" => $all_post_comments
                ]);
            endforeach;
            $this->view("posts/add-comment", [
                "post"             => [
                    "id" => $comment["post_id"],
                ],
                "reply_to_comment" => $comment
            ]);
            ?>
        </ul>
    </div>
</li>