<!-- jQuery -->
<script
    type="text/javascript"
    src="https://code.jquery.com/jquery-3.7.1.slim.min.js"></script>
<script
    type="text/javascript"
    src="https://code.jquery.com/ui/1.14.0/jquery-ui.min.js"
    integrity="sha256-Fb0zP4jE3JHqu+IBB9YktLcSjI1Zc6J2b6gTjB0LpoM="
    crossorigin="anonymous"></script>
<!-- Bulma -->
<link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css" />
<!-- Navbar -->
<link rel="stylesheet" href="public/css/navbar.css?v=<?= time() ?>" />
<script type="text/javascript" src="public/js/navbar.js?v=<?= time() ?>"></script>
<!-- Globals -->
<link rel="stylesheet" href="public/css/main.css?v=<?= time() ?>" />