<!-- jQuery -->
<script
    type="text/javascript"
    src="https://code.jquery.com/jquery-3.7.1.slim.min.js"></script>
<script
    type="text/javascript"
    src="https://code.jquery.com/ui/1.14.0/jquery-ui.min.js"
    integrity="sha256-Fb0zP4jE3JHqu+IBB9YktLcSjI1Zc6J2b6gTjB0LpoM="
    crossorigin="anonymous"></script>
<!-- Bulma -->
<link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css" />
<!-- Icons -->
<script
    crossorigin="anonymous"
    src="https://kit.fontawesome.com/d5cb389dd1.js"></script>
<!-- Local scripts -->
<script
    type="text/javascript"
    data-api-url="<?= API_URL ?>"
    src="public/js/main.js?v=<?= time() ?>"></script>
<script
    type="text/javascript"
    src="public/js/functions.js?v=<?= time() ?>"></script>
<script
    type="text/javascript"
    src="public/js/api.js?v=<?= time() ?>"></script>
<!-- Navbar -->
<script
    type="text/javascript"
    src="public/js/navbar.js?v=<?= time() ?>"></script>
<!-- Local styles -->
<link
    rel="stylesheet"
    href="public/css/main.css?v=<?= time() ?>" />
<link
    rel="stylesheet"
    href="public/css/navbar.css?v=<?= time() ?>" />