<nav class="Navbar navbar is-fixed-top" role="navigation" aria-label="main navigation">
    <div class="navbar-item">

    </div>

    <div class="navbar-brand">
        <a class="Navbar-title navbar-item" href="<?= BASE_URI ?>">
            <?= APP_NAME ?>
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <label class="Navbar-search navbar-item">
        <span class="Navbar-search-icon">
            <i class="fa-solid fa-magnifying-glass"></i>
        </span>
        <span class="Navbar-search-label">
            Pesquisar
            <input
                id="search-input"
                class="Navbar-search-input input is-transparent"
                type="text"
                placeholder="Preencha com uma palavra-chave e aperte Enter..." />
        </span>
    </label>
</nav>