<button
    id="btn-back-to-top"
    class="BackToTop btn btn-danger btn-floating btn-lg"
    type="button"
    title="Voltar ao topo">
    <i class="fas fa-arrow-up"></i>
</button>
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/app/views/components/back-to-top/script.js?v=<?= time() ?>"></script>
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/app/views/components/back-to-top/styles.css?v=<?= time() ?>" />