<?php
extract($comment);

$is_template = json_encode(!(bool)$id || str_contains($id, ":"));
$fullname = "$first_name $last_name";

$initials = get_initials($fullname);
$initials = array_map("strtoupper", $initials);
$initials = implode("", $initials);

if (date_is_valid($created_at)) {
    $created_at = strtotime($created_at);
    $created_at = date(DEFAULT_DISPLAY_DATETIME_FORMAT, $created_at);
}
?>

<li
    class="Comment"
    data-comment-id="<?= $id ?>"
    data-template="<?= $is_template ?>">
    <?php if (!isset($photo) || !file_exists($photo)): ?>
        <div class="Comment-avatar" data-avatar="true">
            <?= $initials ?>
        </div>
    <?php else: ?>
        <img
            class="Comment-photo"
            src="<?= BASE_URI . $photo ?>"
            alt="Foto de <?= $fullname ?>" />
    <?php endif; ?>
    <div class="Comment-content">
        <div class="Comment-info">
            <p class="Comment-author">
                <?= $fullname ?>
            </p>
            <div class="Comment-meta">
                <p class="Comment-time">
                    <?= $created_at ?>
                </p>
                <button class="Comment-reply">
                    Responder
                </button>
            </div>
        </div>
        <div class="Comment-text">
            <?= $text ?>
        </div>
    </div>
</li>