<!DOCTYPE html>
<html lang="pt">

<head>
    <?php
    $this->component("meta-tags", [
        "description" => $description,
        "keywords"    => $keywords
    ])
    ?>
    <title><?= $title ?></title>
    <?php $this->component("dependencies") ?>
    <?php $this->component("fonts") ?>
</head>

<body>
    <?php $this->component("navbar", ["current_path" => $current_path]) ?>
    <?php $this->component("header") ?>
    <main class="Main">
        <?php $this->component("filters", ["current_path" => $current_path]) ?>
    </main>
    <?php $this->component("back-to-top") ?>
    <link 
        rel="stylesheet" 
        href="<?= BASE_URI ?>/app/views/pages/post/styles.css?v=<?= time() ?>" />
</body>

</html>
