<!DOCTYPE html>
<html lang="pt">

<head>
    <?php
    $this->component("meta-tags", [
        "description" => $description,
        "keywords"    => $keywords
    ])
    ?>
    <title><?= $title ?></title>
    <?php $this->component("dependencies") ?>
    <?php $this->component("fonts") ?>
</head>

<body>
    <?php $this->component("navbar", ["active_page" => "home"]) ?>
    <?php $this->component("header") ?>
    <?php $this->component("back-to-top") ?>
</body>

</html>
