<?php
if (date_is_valid($post["created_at"])) {
    $post["created_at"] = strtotime($post["created_at"]);
    $post["created_at"] = date(DEFAULT_DISPLAY_DATETIME_FORMAT, $post["created_at"]);
}

if (date_is_valid($post["updated_at"])) {
    $post["updated_at"] = strtotime($post["updated_at"]);
    $post["updated_at"] = date(DEFAULT_DISPLAY_DATETIME_FORMAT, $post["updated_at"]);
}

$post["category_names"] = explode(",", $post["category_names"]);
$total_categories = count($post["category_names"]);
$last_category_index = $total_categories - 1;
$total_comments = count($post_comments);
?>
<!DOCTYPE html>
<html lang="pt">

<head>
    <?php
    $this->component("meta-tags", [
        "description" => $description,
        "keywords"    => $keywords
    ])
    ?>
    <title><?= $title ?></title>
    <?php $this->component("dependencies") ?>
    <?php $this->component("fonts") ?>
</head>

<body>
    <?php $this->component("navbar") ?>
    <?php $this->component("header") ?>
    <main class="Main">
        <article class="Post-container">
            <h2 class="Post-title title is-2">
                <?= $post["title"] ?>
            </h2>
            <div class="Post-subheader">
                <span class="Post-createdAt"><?= $post["created_at"] ?></span>
                <span class="Post-categories">
                    <?php foreach ($post["category_names"] as $i => $category_name): ?>
                        <a
                            class="Post-category"
                            href="<?= BASE_URI . "/?category=$category_name" ?>">
                            <?= $category_name ?>
                        </a><?= $i !== $last_category_index ? ", " : "" ?>
                    <?php endforeach; ?>
                </span>
            </div>
            <div class="Post-text">
                <?= $post["text"] ?>
            </div>
            <hr class="Post-separator">
            <div class="Post-comments">
                <h3 class="title is-5">
                    <?=
                    $total_comments === 0
                        ? "Nenhum comentário ainda"
                        : ($total_comments === 1
                            ? "1 Comentário"
                            : "$total_comments Comentários")
                    ?>
                </h3>

                <?php $this->component("loader", ["id" => "commentsLoader"]) ?>

                <ul class="Post-comments-list">
                    <?php
                    $this->view("post/comment", [
                        "comment"           => [
                            "id"         => ":id",
                            "first_name" => ":first_name",
                            "last_name"  => ":last_name",
                            "photo"      => ":photo",
                            "text"       => ":text",
                            "created_at" => ":created_at",
                        ],
                        "all_post_comments" => $post_comments
                    ]);
                    foreach ($post_comments as $comment):
                        $this->view("post/comment", [
                            "comment"           => $comment,
                            "all_post_comments" => $post_comments
                        ]);
                    endforeach;
                    ?>
                </ul>

                <div class="AddComment">
                    <header class="AddComment-header">
                        <h3 class="title is-5">
                            Adicionar Comentário
                        </h3>
                        <p class="subtitle is-6">
                            Seu endereço de email não será publicado
                        </p>
                    </header>
                    <form class="AddComment-form" onsubmit="handleSendComment(this, event)">
                        <input
                            type="hidden"
                            name="post_id"
                            value="<?= $post["id"] ?>" />
                        <input
                            required
                            class="input is-normal"
                            type="text"
                            name="fullname"
                            placeholder="Seu nome" />
                        <input
                            required
                            class="input is-normal"
                            type="email"
                            name="email"
                            placeholder="Seu email" />
                        <textarea
                            required
                            class="textarea"
                            name="comment"
                            placeholder="Seu comentário..."
                            rows="10"></textarea>
                        <button class="button is-success is-fullwidth" type="submit">
                            Enviar comentário
                        </button>
                    </form>
                </div>
            </div>
        </article>
        <?php $this->component("filters") ?>
    </main>
    <?php $this->component("back-to-top") ?>
    <link
        rel="stylesheet"
        href="<?= BASE_URI ?>/app/views/pages/post/styles.css?v=<?= time() ?>" />
    <script
        type="text/javascript"
        src="<?= BASE_URI ?>/app/views/pages/post/script.js?v=<?= time() ?>"></script>
</body>

</html>