<div id="modal" class="modal">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title" data-field="title"></p>
            <button 
                class="delete" 
                aria-label="close"
                onclick="window.modal.close()"
            ></button>
        </header>
        <section class="modal-card-body">
            <div class="content" data-field="content"></div>
        </section>
        <footer class="modal-card-foot" data-field="footer">
            <div class="buttons" >
                <button class="button is-success">Save changes</button>
                <button class="button">Cancel</button>
            </div>
        </footer>
    </div>
</div>
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/app/views/components/modal/script.js?v=<?= time() ?>"></script>
