<!DOCTYPE html>
<html lang="pt">

<head>
    <?php
    $this->component("meta-tags", [
        "description" => $description,
        "keywords"    => $keywords
    ])
    ?>
    <title><?= $title ?></title>
    <?php $this->component("fonts") ?>
</head>

<body>
    <iframe src="<?= BASE_URI ?>?admin=1"></iframe>
    <link
        rel="stylesheet"
        href="<?= BASE_URI ?>/app/views/pages/admin/styles.css?v=<?= time() ?>">
</body>

</html>
