<!DOCTYPE html>
<html lang="pt">

<head>
    <?php
    $this->component("meta-tags", [
        "description" => $description,
        "keywords"    => $keywords
    ])
    ?>
    <title><?= $title ?></title>
    <?php $this->component("fonts") ?>
</head>

<body>
    <iframe id="admin-window" src="<?= BASE_URI . $location ?>"></iframe>
    <link
        rel="stylesheet"
        href="<?= BASE_URI ?>/app/views/pages/admin/styles.css?v=<?= $this->version ?>">
    <script 
        type="text/javascript"
        src="<?= BASE_URI ?>/app/views/pages/admin/script.js?v=<?= $this->version ?>"></script>
</body>

</html>
