<?php
$session = $this->request->getSession();
extract($session);

$this->postArticle();
$this->postFilters();
?>
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/app/views/pages/posts/post-article/styles.css?v=<?= $this->version ?>" />
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/app/views/pages/posts/add-comment/styles.css?v=<?= $this->version ?>" />
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/app/views/pages/posts/comment-list/styles.css?v=<?= $this->version ?>" />
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/app/views/pages/posts/comment-card/styles.css?v=<?= $this->version ?>" />
<?php if ($is_admin): ?>
    <script
        type="text/javascript"
        src="<?= BASE_URI ?>/app/views/pages/posts/CategoryEditor.js?v=<?= $this->version ?>"></script>
    <script
        type="text/javascript"
        src="<?= BASE_URI ?>/app/views/pages/posts/PostEditor.js?v=<?= $this->version ?>"></script>
    <script
        type="text/javascript"
        <?php foreach ($post as $key => $value): ?>
            <?php if ($key !== "text"): ?>
                data-<?= $key ?>="<?= $value ?>"
            <?php endif; ?>
        <?php endforeach; ?>
        src="<?= BASE_URI ?>/app/views/pages/posts/script.js?v=<?= $this->version ?>"></script>
<?php endif; ?>
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/app/views/pages/posts/handlers.js?v=<?= $this->version ?>"></script>
