<?php
$session = $this->request->getSession();
extract($session);

$this->postArticle();
$this->postFilters();
?>
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/app/views/pages/posts/post-article/styles.css?v=<?= time() ?>" />
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/app/views/pages/posts/add-comment/styles.css?v=<?= time() ?>" />
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/app/views/pages/posts/comment-list/styles.css?v=<?= time() ?>" />
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/app/views/pages/posts/comment-card/styles.css?v=<?= time() ?>" />
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/app/views/pages/posts/script.js?v=<?= time() ?>"></script>
<?php if ($is_admin): ?>
    <script
        type="text/javascript"
        src="<?= BASE_URI ?>/app/views/pages/posts/text-editor.js?v=<?= time() ?>"></script>
<?php endif; ?>
