<?php 
$session = $this->request->getSession();
extract($session);
extract($settings);
?>
<header class="Header">
    <div class="Header-inner">
        <h1 class="Header-title title is-3">
            <a 
                href="<?= BASE_URI ?>" 
                <?php if ($is_authenticated): ?> 
                    data-settings="blog_name"
                <?php endif; ?>
            >
                <?= $blog_name ?>
            </a>
        </h1>
        <p 
            class="Header-subtitle subtitle" 
            <?php if ($is_authenticated): ?> 
                data-settings="blog_catchline"
            <?php endif; ?>
        >
            <?= $blog_catchline ?>
        </p>
    </div>
</header>
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/app/views/components/header/styles.css?v=<?= time() ?>" />
<style type="text/css">
    .Header {
        --header-background-image: url("<?= BASE_URI . "/public/images/header-plant.png" ?>");
    }
</style>
