<?php 
$session = $this->request->getSession();
$settings = $session["settings"];
extract($settings);
?>
<header class="Header">
    <div class="Header-inner">
        <h1 class="Header-title title is-3">
            <a href="<?= BASE_URI ?>" data-settings="blog_name">
                <?= $blog_name ?>
            </a>
        </h1>
        <p class="Header-subtitle subtitle" data-settings="blog_name">
            <?= $blog_catchline ?>
        </p>
    </div>
</header>
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/app/views/components/header/styles.css?v=<?= time() ?>" />
<style type="text/css">
    .Header {
        --header-background-image: url("<?= BASE_URI . "/public/images/header-plant.png" ?>");
    }
</style>
