<nav
    class="Navbar navbar is-fixed-top"
    role="navigation"
    aria-label="main navigation">

    <div class="navbar-brand">
        <a
            class="navbar-burger"
            role="button"
            aria-label="menu"
            aria-expanded="false"
            data-target="main-menu">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="main-menu" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item<?= $current_path === "/" ? " active" : "" ?>" href="<?= BASE_URI ?>">
                Início
            </a>
            <a class="navbar-item<?= $current_path === "/about" ? " active" : "" ?>" href="<?= BASE_URI ?>/about">
                Sobre
            </a>
            <a class="navbar-item<?= $current_path === "/contact" ? " active" : "" ?>" href="<?= BASE_URI ?>/contact">
                Contato
            </a>
            <a class="navbar-item<?= $current_path === "/archives" ? " active" : "" ?>" href="<?= BASE_URI ?>/archives">
                Arquivos
            </a>
        </div>
    </div>
</nav>
<script
    type="text/javascript"
    src="<?= BASE_URI ?>/app/views/components/navbar/script.js?v=<?= time() ?>"></script>
<link
    rel="stylesheet"
    href="<?= BASE_URI ?>/app/views/components/navbar/styles.css?v=<?= time() ?>" />
